require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PublicRelationsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PublicRelation. As you add validations to PublicRelation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublicRelationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    xit "assigns all public_relations as @public_relations" do
      public_relation = PublicRelation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:public_relations)).to eq([public_relation])
    end
  end

  describe "GET show" do
    xit "assigns the requested public_relation as @public_relation" do
      public_relation = PublicRelation.create! valid_attributes
      get :show, {:id => public_relation.to_param}, valid_session
      expect(assigns(:public_relation)).to eq(public_relation)
    end
  end

  describe "GET new" do
    xit "assigns a new public_relation as @public_relation" do
      get :new, {}, valid_session
      expect(assigns(:public_relation)).to be_a_new(PublicRelation)
    end
  end

  describe "GET edit" do
    xit "assigns the requested public_relation as @public_relation" do
      public_relation = PublicRelation.create! valid_attributes
      get :edit, {:id => public_relation.to_param}, valid_session
      expect(assigns(:public_relation)).to eq(public_relation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      xit "creates a new PublicRelation" do
        expect {
          post :create, {:public_relation => valid_attributes}, valid_session
        }.to change(PublicRelation, :count).by(1)
      end

      xit "assigns a newly created public_relation as @public_relation" do
        post :create, {:public_relation => valid_attributes}, valid_session
        expect(assigns(:public_relation)).to be_a(PublicRelation)
        expect(assigns(:public_relation)).to be_persisted
      end

      xit "redirects to the created public_relation" do
        post :create, {:public_relation => valid_attributes}, valid_session
        expect(response).to redirect_to(PublicRelation.last)
      end
    end

    describe "with invalid params" do
      xit "assigns a newly created but unsaved public_relation as @public_relation" do
        post :create, {:public_relation => invalid_attributes}, valid_session
        expect(assigns(:public_relation)).to be_a_new(PublicRelation)
      end

      xit "re-renders the 'new' template" do
        post :create, {:public_relation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      xit "updates the requested public_relation" do
        public_relation = PublicRelation.create! valid_attributes
        put :update, {:id => public_relation.to_param, :public_relation => new_attributes}, valid_session
        public_relation.reload
        skip("Add assertions for updated state")
      end

      xit "assigns the requested public_relation as @public_relation" do
        public_relation = PublicRelation.create! valid_attributes
        put :update, {:id => public_relation.to_param, :public_relation => valid_attributes}, valid_session
        expect(assigns(:public_relation)).to eq(public_relation)
      end

      xit "redirects to the public_relation" do
        public_relation = PublicRelation.create! valid_attributes
        put :update, {:id => public_relation.to_param, :public_relation => valid_attributes}, valid_session
        expect(response).to redirect_to(public_relation)
      end
    end

    describe "with invalid params" do
      xit "assigns the public_relation as @public_relation" do
        public_relation = PublicRelation.create! valid_attributes
        put :update, {:id => public_relation.to_param, :public_relation => invalid_attributes}, valid_session
        expect(assigns(:public_relation)).to eq(public_relation)
      end

      xit "re-renders the 'edit' template" do
        public_relation = PublicRelation.create! valid_attributes
        put :update, {:id => public_relation.to_param, :public_relation => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    xit "destroys the requested public_relation" do
      public_relation = PublicRelation.create! valid_attributes
      expect {
        delete :destroy, {:id => public_relation.to_param}, valid_session
      }.to change(PublicRelation, :count).by(-1)
    end

    xit "redirects to the public_relations list" do
      public_relation = PublicRelation.create! valid_attributes
      delete :destroy, {:id => public_relation.to_param}, valid_session
      expect(response).to redirect_to(public_relations_url)
    end
  end

end
