require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TweetsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tweet. As you add validations to Tweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TweetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    xit "assigns all tweets as @tweets" do
      tweet = Tweet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tweets)).to eq([tweet])
    end
  end

  describe "GET show" do
    xit "assigns the requested tweet as @tweet" do
      tweet = Tweet.create! valid_attributes
      get :show, {:id => tweet.to_param}, valid_session
      expect(assigns(:tweet)).to eq(tweet)
    end
  end

  describe "GET new" do
    xit "assigns a new tweet as @tweet" do
      get :new, {}, valid_session
      expect(assigns(:tweet)).to be_a_new(Tweet)
    end
  end

  describe "GET edit" do
    xit "assigns the requested tweet as @tweet" do
      tweet = Tweet.create! valid_attributes
      get :edit, {:id => tweet.to_param}, valid_session
      expect(assigns(:tweet)).to eq(tweet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      xit "creates a new Tweet" do
        expect {
          post :create, {:tweet => valid_attributes}, valid_session
        }.to change(Tweet, :count).by(1)
      end

      xit "assigns a newly created tweet as @tweet" do
        post :create, {:tweet => valid_attributes}, valid_session
        expect(assigns(:tweet)).to be_a(Tweet)
        expect(assigns(:tweet)).to be_persisted
      end

      xit "redirects to the created tweet" do
        post :create, {:tweet => valid_attributes}, valid_session
        expect(response).to redirect_to(Tweet.last)
      end
    end

    describe "with invalid params" do
      xit "assigns a newly created but unsaved tweet as @tweet" do
        post :create, {:tweet => invalid_attributes}, valid_session
        expect(assigns(:tweet)).to be_a_new(Tweet)
      end

      xit "re-renders the 'new' template" do
        post :create, {:tweet => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      xit "updates the requested tweet" do
        tweet = Tweet.create! valid_attributes
        put :update, {:id => tweet.to_param, :tweet => new_attributes}, valid_session
        tweet.reload
        skip("Add assertions for updated state")
      end

      xit "assigns the requested tweet as @tweet" do
        tweet = Tweet.create! valid_attributes
        put :update, {:id => tweet.to_param, :tweet => valid_attributes}, valid_session
        expect(assigns(:tweet)).to eq(tweet)
      end

      xit "redirects to the tweet" do
        tweet = Tweet.create! valid_attributes
        put :update, {:id => tweet.to_param, :tweet => valid_attributes}, valid_session
        expect(response).to redirect_to(tweet)
      end
    end

    describe "with invalid params" do
      xit "assigns the tweet as @tweet" do
        tweet = Tweet.create! valid_attributes
        put :update, {:id => tweet.to_param, :tweet => invalid_attributes}, valid_session
        expect(assigns(:tweet)).to eq(tweet)
      end

      xit "re-renders the 'edit' template" do
        tweet = Tweet.create! valid_attributes
        put :update, {:id => tweet.to_param, :tweet => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    xit "destroys the requested tweet" do
      tweet = Tweet.create! valid_attributes
      expect {
        delete :destroy, {:id => tweet.to_param}, valid_session
      }.to change(Tweet, :count).by(-1)
    end

    xit "redirects to the tweets list" do
      tweet = Tweet.create! valid_attributes
      delete :destroy, {:id => tweet.to_param}, valid_session
      expect(response).to redirect_to(tweets_url)
    end
  end

end
